### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by ruimartinsptl** [acidjunk/starlette-opentracing#3]
Inside your Fast API Example ( [example/fastapi/requirements.txt](https://github.com/acidjunk/starlette-opentracing/blob/afccbe70f0bf3637da65eb8ae2ed2c3b4cc04aad/example/fastapi/requirements.txt) ) , you have:

```text
fastapi
jaeger-client
opentracing_instrumentation
requests
-e git://github.com/acidjunk/starlette-opentracing.git#egg=Starlette-OpenTracing
tornado==5.1.1  # pin to last release for 5, implicit install of 6 gives errors
uvicorn
```

This was made 9 months ago, and didn't was released Python 3.9, however, I think that Tornado version is not a problem now with python 3.9

I tried this example, and my `requirements.txt` are:

```text
fastapi==0.63.0
uvicorn==0.13.3
requests==2.25.1

jaeger-client==4.3.0
opentracing-instrumentation==3.3.1
Starlette-OpenTracing==0.1.0
```

With Python 3.8 I got this error:
```text
Traceback (most recent call last):  File "app.py", line 11, in <module>    from opentracing_instrumentation.client_hooks import install_all_patches  File "/usr/local/lib/python3.8/site-packages/opentracing_instrumentation/__init__.py", line 21, in <module>    from .request_context import get_current_span  # noqa  File "/usr/local/lib/python3.8/site-packages/opentracing_instrumentation/request_context.py", line 26, in <module>    from opentracing.scope_managers.tornado import TornadoScopeManager  File "/usr/local/lib/python3.8/site-packages/opentracing/scope_managers/tornado.py", line 24, in <module>    import tornado.stack_contextModuleNotFoundError: No module named 'tornado.stack_context'
```

However with Python 3.9.1 works perfectly :)

I think you can update your requirements in your example.

**Comment by acidjunk** [comment]
Sorry for the late answer. @ SURF we switched to opentelemetry; do you mind opening a PR?

**Comment by ruimartinsptl** [comment]
Sure @acidjunk , I just created :)
https://github.com/acidjunk/starlette-opentracing/pull/5

**Comment by acidjunk** [comment]
Cool thanks. Merged.
Will try to create a new build this week.
